baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
pygmentsUseClasses = true
[permalinks]
  posts = "/:year/:month/:day/:title/"
[markup.goldmark.renderer]
	unsafe = true
