baseURL = "https://ericroberts.ca"
languageCode = "en-us"
title = "My New Hugo Site"
pygmentsUseClasses = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[markup.goldmark.renderer]
	unsafe = true
