baseURL = "https://naughty-swanson-d227ad.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"
pygmentsUseClasses = true
[permalinks]
  posts = "/:year/:month/:day/:title/"
[markup.goldmark.renderer]
	unsafe = true
